version: '3.8'

services:

  front-end:
    container_name: front_todos
    build:
      context: ./vue_todos
      dockerfile: Dockerfile
    ports:
      - '8081:8080'

  back-end:
    container_name: api_todos
    build: 
      context: ./web-service-gin
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    command: 
      ./api